companies/urls.py
from django.urls import path
from companies import views

app_name = 'company'

urlpatterns = [
    path('', views.CompaniesIndex.as_view(), name='index'),
    # path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('delete/<int:pk>/', views.DeleteCompanyView.as_view(), name='remove_company'),
    path('update/<int:pk>/', views.UpdateCompanyView.as_view(), name='update_company'),
    path('add/', views.CreateCompanyView.as_view(), name='create_company'),
    ]

numeAplicatie/urls.py
from django.urls import path
from numeAplicatie import views

app_name = 'app1'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name='home'),
    # path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('update/<int:pk>/', views.UpdateIndex.as_view(), name='update'),
    path('add_location/', views.CreateLocation.as_view(), name='add_new_location'),
    ]

numeProiect/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('numeAplicatie.urls')),
    path('companies/', include('companies.urls')),
]

companies/models.py
from django.db import models

from numeAplicatie.models import Location


class Companies(models.Model):
    name = models.CharField('Company Name', max_length=200)
    website = models.CharField('Website', max_length=200)
    location = models.ForeignKey(Location, on_delete=models.ForeignKey)

numeAplicatie/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    # cityChoices = (('Bucuresti', 'Bucuresti'), ('Craiova', 'Craiova'))
    country = models.CharField('Country', max_length=100, blank=True, null=True)
    city = models.CharField('City', max_length=100, blank=True, null=True)

    def __str__(self):
        return '{}-{}'.format(str(self.country), str(self.city))

companies/forms.py
from django import forms
from django.forms import TextInput, Select

from companies.models import Companies


class CompaniesForm(forms.ModelForm):
    class Meta:
        model = Companies
        fields = ['name', 'website', 'location']

        widgets = {
            'name': TextInput(attrs={'placeholder': 'Name of company', 'class': 'form-control'}),
            'website': TextInput(attrs={'placeholder': 'Website of company', 'class': 'form-control'}),
            'location': Select(attrs={'class': 'form-control'}),
        }

numeAplicatie/forms.py
from django import forms
from django.forms import TextInput, Select

from numeAplicatie.models import Location


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['country', 'city']

        widgets = {
            'city': TextInput(attrs={'placeholder': 'City', 'class': 'field'}),
            'country': TextInput(attrs={'placeholder': 'Country', 'class': 'field'}),
        }

    def __init__(self, test, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.test = test

    def clean(self):
        cleaned_data = self.cleaned_data
        city_val = self.cleaned_data['city']
        country_val = self.cleaned_data['country']
        if self.test:
            all_locations = Location.objects.all().exclude(id=self.test)
        else:
            all_locations = Location.objects.all()
        for location in all_locations:
            if city_val == location.city and country_val == location.country:
                self._errors['city'] = 'Duplicate entry'
        return cleaned_data

companies/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView

from companies.forms import CompaniesForm
from companies.models import Companies


class CompaniesIndex(ListView):
    model = Companies
    context_object_name = 'all_companies'
    template_name = 'companies/companies_index.html'


class CreateCompanyView(CreateView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:index')


class UpdateCompanyView(UpdateView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:update_company', args=[self.object.id])


class DeleteCompanyView(DeleteView):
    model = Companies
    template_name = 'companies/company_form.html'
    form_class = CompaniesForm

    def get_success_url(self):
        return reverse('company:index')

numeAplicatie/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView

from numeAplicatie.forms import LocationForm
from numeAplicatie.models import Location


class HomeIndex(ListView):
    model = Location
    template_name = 'locations_index.html'
    context_object_name = 'all_locations'




class CreateLocation(CreateView):
    model = Location
    form_class = LocationForm
    # fields = ['country']
    template_name = 'location.html'

    def get_form_kwargs(self):
        kwargs = super(CreateLocation, self).get_form_kwargs()
        kwargs.update({'test': None})
        return kwargs

    def get_success_url(self):
        return reverse('app1:home')


class UpdateIndex(UpdateView):
    model = Location
    form_class = LocationForm
    template_name = 'location.html'

    def get_queryset(self):
        return self.model.objects.filter(id=4)

    def get_form_kwargs(self):
        kwargs = super(UpdateIndex, self).get_form_kwargs()
        kwargs.update({'test': self.kwargs['pk']})
        return kwargs

    def get_success_url(self):
        return reverse('app1:home')

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
</head>

<body>
<section class="hero is-primary is-fullheight">

    <div class="navbar-end">
        <a href="#" class="navbar-item">
            Home
        </a>
        <a href="#" class="navbar-item">
            Profile
        </a>
        <a href="#" class="navbar-item">
            Jobs
        </a>
        <a href="{% url 'company:index' %}" class="navbar-item">
            Companies
        </a>
        <a href="{% url 'app1:home' %}" class="navbar-item">
            Location
        </a>
        <a href="#" class="navbar-item">
            Login
        </a>
        <a href="#" class="navbar-item">
            Sign Up
        </a>
        <a href="#" class="navbar-item">
            Logout
        </a>

    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</section>
</body>

</html>

templates/companies/companies_index.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div><a class="btn btn-danger" href="{% url 'company:create_company' %}">Add company</a></div>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Company Name</th>
            <th scope="col">Website</th>
            <th scope="col">Location</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% if all_companies %}
            {% for x in all_companies %}
                <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{ x.name|upper }}</td>
                    <td>{{ x.website|upper }}</td>
                    <td>Country {{ x.location.country }} - city {{ x.location.city }}</td>
                    <td><a class="btn btn-secondary" href="{% url 'company:update_company' x.id %}">EDIT</a>
                        <a class="btn btn-secondary" href="{% url 'company:remove_company' x.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="5" class="text-center">No data available</td></tr>
        {% endif %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
{% endblock %}

templates/companies/company_form.html
{% extends 'base.html' %}
{% block content %}
     <form method="POST">
        {% csrf_token %}
         <div class="box">
            <div class="field">
                {% for field in form %}
                    <div class="form-control">{{ field.label }} {{ field }}
                    </div>
                    <div>{{ field.errors }}</div>
                {% endfor %}
            </div>
           <button type="submit" class="btn btn-info">Salveaza</button>
         </div>
     <form>
{% endblock %}

templates/location.html
{% extends "base.html" %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        <div class="box">
            <div class="field" style="background: red;">{{ error }}</div>
            <div class="field">

                {% for field in form %}
                    <div class="control">
                        {{ field.label }}
                        {{ field }}
                    {{ field.errors }}
                    </div>
                {% endfor %}

            </div>

            <button class="button is-block is-info is-large is-fullwidth">Salveaza</button>
        </div>
    </form>
{% endblock %}

templates/locations_edit.html
{% extends "base.html" %}
{% block content %}



{% endblock %}

templates/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <div class="center"><a type="button" class="btn btn-secondary" href="{% url 'app1:add_new_location' %}">Add new location</a></div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">CITY</th>
            <th scope="col">ACTIONS</th>
        </tr>
        </thead>
        <tbody>
        {% for x in all_locations %}
            <tr>
                <td scope="row">{{ forloop.counter }}</td>
                <td>{{ x.city|upper }}</td>
                <td><a class="btn btn-secondary" href="{% url 'app1:update' x.id %}">EDIT</a>
                <a class="btn btn-secondary" id="delete_{{ x.id }}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/save_edit_locations.js"></script>
{% endblock %}